apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: curto
spec:
  serviceName: "curto"
  replicas: 2
  selector:
    matchLabels:
      app: curto
  template:
    metadata:
      labels:
        app: curto
    spec:
      containers:
      - image: mfvitale/curto:latest
        name: curto
        env:
         - name: REDIS_ENDPOINT
           valueFrom:
             secretKeyRef:
               name: redis-secrets
               key: REDIS_ENDPOINT
         - name: REDIS_USERNAME
           valueFrom:
             secretKeyRef:
               name: redis-secrets
               key: REDIS_USERNAME
         - name: REDIS_PASSWORD
           valueFrom:
             secretKeyRef:
               name: redis-secrets
               key: REDIS_PASSWORD
         - name: POD_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name

---

apiVersion: v1
kind: Service
metadata:
  name: curto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "curto"
    port: 8080
  selector:
    app: curto
