apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: redis-secrets
  envs:
  - redis-secrets.env
images:
- name: mfvitale/curto
  newName: mfvitale/curto
  newTag: $IMAGE_TAG
resources:
- k8s.yml
