name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      uses: okteto/actions/build@v3.1
      with:
        file: build/Dockerfile
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: ${{ secrets.DOCKER_USERNAME }}/curto:${{ github.sha }}
    - name: Get Kubeconfig
      uses: okteto/actions/namespace@v3.1
      id: url-shortner-mfvitale
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: url-shortner-mfvitale
    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: pr-${{ github.event.number }}
        timeout: 8m
        filename: deploy/okteto-pipeline.yml
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with:
        time: '30s'
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://curto-url-shortner-mfvitale.cloud.okteto.net"
        expected-statuses: "200"
